pipeline {
    agent any

    stages {
        stage ('Configure build info') {
            steps {
                rtBuildInfo (
                    // Build retention:
                    maxBuilds: 1,
                    maxDays: 2,
                    doNotDiscardBuilds: ["3"],
                    deleteBuildArtifacts: true
                    // Using the Jenkins job's build name and number.
                )
            }
        }

        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: SERVER_ID // Obtain an Artifactory server instance, defined in Jenkins --> Manage:
                )
            }
        }
    }
}
