node {
    git url: 'https://github.com/jfrogdev/project-examples.git'
    def filePathPrefix = 'jenkins-pipeline-examples/props-example/'

    // Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server SERVER_ID

    // Create the upload spec.
    def uploadSpec = """{
        "files": [
                {
                    "pattern": "jenkins-pipeline-examples/files/ArtifactoryPipeline.zip",
                    "target": "libs-snapshot-local",
                    "props": "p1=v1;p2=v2"
                },
                {
                    "pattern": "jenkins-pipeline-examples/files/ArtifactoryPipelineNoProps.zip",
                    "target": "libs-snapshot-local"
                }
            ]
        }"""

    // Upload to Artifactory.
    def buildInfo1 = server.upload uploadSpec

    // Create the download spec.
    def downloadSpec = """{
        "files": [
                {
                    "pattern": "libs-snapshot-local/*(Pipeline).zip",
                    "target": "Bazinga/{1}/",
                    "props": "p1=v1;p2=v2"
                }
            ]
        }"""

    // Download from Artifactory.
    def buildInfo2 = server.download downloadSpec

    // Merge the upload and download build-info objects.
    buildInfo1.append buildInfo2

    // Publish the build to Artifactory
    server.publishBuildInfo buildInfo1
}
