node {
    def server
    def rtDocker
    def buildInfo

    stage ('Artifactory configuration') {
        // Obtain an Artifactory server instance, defined in Jenkins --> Manage Jenkins --> Configure System:
        server = Artifactory.server SERVER_ID
        // Host:
        // On OSX: "tcp://127.0.0.1:1234"
        // On Linux can be omitted or null
        rtDocker = Artifactory.docker server: server, host: HOST_NAME
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('Pull an image from Artifactory') {
       rtDocker.pull ARTIFACTORY_DOCKER_REGISTRY + '/hello-world:latest', 'docker-remote', buildInfo
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}