node {
    def server = Artifactory.server SERVER_ID
    def rtPip = Artifactory.newPipBuild()
    def buildInfo
    def virtual_env_activation = "source /Users/myUser/venv-example/bin/activate" // pip virtual-environment activation command

    stage ('Clone') {
        git url: 'https://github.com/jfrog/project-examples.git'
    }

    stage ('Artifactory configuration') {
        rtPip.resolver repo: 'pypi-virtual', server: server
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('Pip install') {
        rtPip.install buildInfo: buildInfo, args: "-r python-example/requirements.txt", envActivation: virtual_env_activation
    }

    stage ('Package and create distribution archives') {
        sh '''
            $virtual_env_activation
            cd python-example
            python setup.py sdist bdist_wheel
        '''
    }

    stage ('Upload packages') {
        def uploadSpec = """{
            "files": [
                {
                    "pattern": "python-example/dist/",
                    "target": "pypi-virtual/"
                }
            ]
        }"""
        server.upload buildInfo: buildInfo, spec: uploadSpec
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}