node {
    stage 'Build'
        git url: 'https://github.com/jfrogdev/project-examples.git'

    stage 'Artifactory configuration'
        def server = Artifactory.newServer url: SERVER_URL, credentialsId: CREDENTIALS
        def artifactoryGradle = Artifactory.newGradleBuild()
        artifactoryGradle.tool = GRADLE_TOOL // Tool name from Jenkins configuration
        artifactoryGradle.deployer repo:'ext-release-local', server: server
        artifactoryGradle.resolver repo:'remote-repos', server: server

    stage 'Exec Gradle'
        def buildInfo = artifactoryGradle.run rootDir: "gradle-examples/4/gradle-example-ci-server/", buildFile: 'build.gradle', tasks: 'clean artifactoryPublish'

    stage 'Publish build info'
        server.publishBuildInfo buildInfo
}