pipeline {
    /**
     *  In this example, the agent's Dockerfile is within the repository.
     *  Therefore, you must use this example only in "Multibranch Pipeline" or a "Pipeline from SCM".
     *  More information here: https://jenkins.io/doc/book/pipeline/syntax/#agent under "dockerfile".
     */
    agent {
        dockerfile {
            dir 'jenkins-examples/pipeline-examples/resources/npm'
        }
    }

    environment {
        npm_config_cache = 'npm-cache'
    }

    stages {
        stage('Artifactory configuration') {
            steps {
                rtServer(
                        id: "ARTIFACTORY_SERVER",
                        url: SERVER_URL,
                        credentialsId: CREDENTIALS
                )

                rtNpmResolver(
                        id: "NPM_RESOLVER",
                        serverId: "ARTIFACTORY_SERVER",
                        repo: "npm-remote"
                )

                rtNpmDeployer(
                        id: "NPM_DEPLOYER",
                        serverId: "ARTIFACTORY_SERVER",
                        repo: "npm-local"
                )
            }
        }

        stage('Exec npm install') {
            steps {
                rtNpmInstall(
                        path: "npm-example",
                        resolverId: "NPM_RESOLVER"
                )
            }
        }

        stage('Exec npm publish') {
            steps {
                rtNpmPublish(
                        path: "npm-example",
                        deployerId: "NPM_DEPLOYER"
                )
            }
        }

        stage('Publish build info') {
            steps {
                rtPublishBuildInfo(
                        serverId: "ARTIFACTORY_SERVER"
                )
            }
        }
    }
}