node {
    git url: 'https://github.com/JFrog/project-examples.git'

    // Obtain an Artifactory server instance, defined in Jenkins --> Manage:
    def server = Artifactory.server SERVER_ID

    // Read the upload spec which was downloaded from github.
    def uploadSpec = readFile 'jenkins-examples/pipeline-examples/resources/props-upload.json'
    // Upload to Artifactory.
    def buildInfo1 = server.upload spec: uploadSpec

    // Read the set-props spec.
    def setPropsSpec = readFile 'jenkins-examples/pipeline-examples/resources/set-props.json'
    // Set properties on the matching artifacts.
    server.setProps spec: setPropsSpec, props: "p3=v3", failNoOp: true

    // Read the download spec.
    def downloadSpec = readFile 'jenkins-examples/pipeline-examples/resources/props-download.json'
    // Download from Artifactory.
    def buildInfo2 = server.download spec: downloadSpec

    // Merge the upload and download build-info objects.
    buildInfo1.append buildInfo2

    // Publish the build to Artifactory
    server.publishBuildInfo buildInfo1

    // Read the delete-props spec.
    def deletePropsSpec = readFile 'jenkins-examples/pipeline-examples/resources/delete-props.json'
    // Delete properties on the matching artifacts.
    server.deleteProps spec: deletePropsSpec, props: "p1,p2", failNoOp: true
}
