node {
    git url: 'https://github.com/JFrog/project-examples.git'

    // Obtain an Artifactory server instance, defined in Jenkins --> Manage:
    def server = Artifactory.server SERVER_ID

    // Read the upload spec which was downloaded from github.
    def uploadSpec = readFile 'jenkins-examples/pipeline-examples/resources/props-upload.json'
    // Upload to Artifactory.
    def buildInfo1 = server.upload spec: uploadSpec

    // Read the upload spec and upload files to Artifactory.
    def downloadSpec = readFile 'jenkins-examples/pipeline-examples/resources/props-download.json'
    def buildInfo2 = server.download spec: downloadSpec

    // Merge the upload and download build-info objects.
    buildInfo1.append buildInfo2

    // Publish the build to Artifactory
    server.publishBuildInfo buildInfo1
}
