pipeline {
    agent any

    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "https://github.com/jfrog/project-examples.git"
            }
        }

        stage ('Upload') {
            steps {
                rtUpload (
                    serverId: SERVER_ID, // Obtain an Artifactory server instance, defined in Jenkins --> Manage:
                    specPath: 'jenkins-examples/pipeline-examples/resources/props-upload.json'
                )
            }
        }

        stage ('Set Props') {
            steps {
                rtSetProps (
                    serverId: SERVER_ID,
                    specPath: 'jenkins-examples/pipeline-examples/resources/set-props.json',
                    props: "p3=v3",
                    failNoOp: true
                )
            }
        }

        stage ('Download') {
            steps {
                rtDownload (
                    serverId: SERVER_ID,
                    specPath: 'jenkins-examples/pipeline-examples/resources/props-download.json'
                )
            }
        }

        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: SERVER_ID
                )
            }
        }

        stage ('Delete Props') {
            steps {
                rtDeleteProps (
                    serverId: SERVER_ID,
                    specPath: 'jenkins-examples/pipeline-examples/resources/delete-props.json',
                    props: "p1,p2",
                    failNoOp: true
                )
            }
        }
    }
}
