node {
    def server
    def buildInfo
    def rtGradle
    
    stage ('Clone') {
        git url: 'https://github.com/jfrog/project-examples.git'
    }
 
    stage ('Artifactory configuration') {
        // Obtain an Artifactory server instance, defined in Jenkins --> Manage Jenkins --> Configure System:
        server = Artifactory.server SERVER_ID

        rtGradle = Artifactory.newGradleBuild()
        rtGradle.tool = GRADLE_TOOL // Tool name from Jenkins configuration
        rtGradle.deployer repo: ARTIFACTORY_LOCAL_RELEASE_REPO, server: server
        rtGradle.resolver repo: ARTIFACTORY_VIRTUAL_RELEASE_REPO, server: server
        rtGradle.deployer.deployArtifacts = false // Disable artifacts deployment during Gradle run
        
        buildInfo = Artifactory.newBuildInfo()
    }
 
    stage ('Test') {
        rtGradle.run rootDir: 'gradle-examples/gradle-example-ci-server/', tasks: 'clean test'
    }
 
    stage ('Deploy') {
        rtGradle.run rootDir: 'gradle-examples/gradle-example-ci-server/', tasks: 'artifactoryPublish', buildInfo: buildInfo
        rtGradle.deployer.deployArtifacts buildInfo
    }
    
    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}

