node {
    git url: 'https://github.com/JFrog/project-examples.git'

    // Obtain an Artifactory server instance, defined in Jenkins --> Manage:
    def server = Artifactory.server SERVER_ID

    // Create the upload spec.
    def uploadSpec = """{
        "files": [
                {
                    "pattern": "jenkins-examples/pipeline-examples/resources/ArtifactoryPipeline.zip",
                    "target": "libs-snapshot-local",
                    "props": "p1=v1;p2=v2"
                },
                {
                    "pattern": "jenkins-examples/pipeline-examples/resources/ArtifactoryPipelineNoProps.zip",
                    "target": "libs-snapshot-local"
                }
            ]
        }"""

    // Upload to Artifactory.
    def buildInfo1 = server.upload spec: uploadSpec

    // Create the download spec.
    def downloadSpec = """{
        "files": [
                {
                    "pattern": "libs-snapshot-local/*(Pipeline).zip",
                    "target": "Bazinga/{1}/",
                    "props": "p1=v1;p2=v2"
                }
            ]
        }"""

    // Download from Artifactory.
    def buildInfo2 = server.download spec: downloadSpec

    // Merge the upload and download build-info objects.
    buildInfo1.append buildInfo2

    // Publish the build to Artifactory
    server.publishBuildInfo buildInfo1
}
