node {
    def server
    def rtDocker
    def buildInfo

    stage ('Clone') {
        git url: 'https://github.com/jfrog/project-examples.git'
    }

    stage ('Artifactory configuration') {
        // Obtain an Artifactory server instance, defined in Jenkins --> Manage Jenkins --> Configure System:
        server = Artifactory.server SERVER_ID
        // Host:
        // On OSX: "tcp://127.0.0.1:1234"
        // On Linux can be omitted or null
        rtDocker = Artifactory.docker server: server, host: HOST_NAME
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('Add properties') {
        // Attach custom properties to the published artifacts:
        rtDocker.addProperty("project-name", "docker1").addProperty("status", "stable")
    }

    stage ('Build docker image') {
        docker.build(ARTIFACTORY_DOCKER_REGISTRY + '/hello-world:latest', 'jenkins-examples/pipeline-examples/resources')
    }

    stage ('Push image to Artifactory') {
        rtDocker.push ARTIFACTORY_DOCKER_REGISTRY + '/hello-world:latest', 'docker-local', buildInfo
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}