#!/bin/bash
# this script sets up Jenkins job to create rpm per name
# Inputs
# $1 = GitHub user name
# $2 = Build Number that is passed by Jenkins
# $3 = Current worksapce

STUDENT_DEFINE="_ghubid $1"
BUILD_DEFINE="_build_number $2"
RPMDIR_DEFINE="_topdir $3/rpmbuild"
RPMFILENAME="_rpmfilename $1"

workingDir=$3
cd $workingDir

wardir=org/jfrog/test/multi3/*/multi3-*.war

# Setup rpmbuild environment
mkdir -p rpmbuild
cd rpmbuild
for dir in BUILD RPMS SOURCES SPECS SRPMS
do
 [[ -d $dir ]] && rm -Rf $dir
  mkdir $dir
done
cd $workingDir

# Put the training spec in the SPEC folder and source in Build folder
cp $wardir rpmbuild/BUILD/$1.war
cp $workingDir/maven-example/training.spec rpmbuild/SPECS/.

# Parse the release version


# remove the *.war file else it will reuse it the next time.
#rm -Rf $wardir
cd rpmbuild

rpmbuild --define "RPMFILENAME" --define "$RPMDIR_DEFINE" --define "$STUDENT_DEFINE" --define "$BUILD_DEFINE" -ba SPECS/training.spec
