node {
    git url: 'https://github.com/jfrogdev/project-examples.git'
    def filePathPrefix = 'jenkins-pipeline-examples/props-example/'

    // Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server SERVER_ID

    // Read the upload spec which was downloaded from github.
    def uploadSpec = readFile "${filePathPrefix}upload.json"
    // Upload to Artifactory.
    def buildInfo1 = server.upload uploadSpec

    // Read the upload spec and upload files to Artifactory.
    def downloadSpec = readFile "${filePathPrefix}download.json"
    def buildInfo2 = server.download downloadSpec

    // Merge the upload and download build-info objects.
    buildInfo1.append buildInfo2

    // Publish the build to Artifactory
    server.publishBuildInfo buildInfo1
}
