node {
    git url: 'https://github.com/jfrogdev/project-examples.git'

    // Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server SERVER_ID

    // Read the upload spec which was downloaded from github.
    def uploadSpec = readFile 'jenkins-pipeline-examples/resources/props-upload.json'
    // Upload to Artifactory.
    def buildInfo1 = server.upload spec: uploadSpec

    // Read the upload spec and upload files to Artifactory.
    def downloadSpec = readFile 'jenkins-pipeline-examples/resources/props-download.json'
    def buildInfo2 = server.download spec: downloadSpec

    // Merge the upload and download build-info objects.
    buildInfo1.append buildInfo2

    // Publish the build to Artifactory
    server.publishBuildInfo buildInfo1
}
